FROM golang:1.19 as build-stage

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -o bin/slurm-sidecar cmd/sidecars/slurm/main.go


# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/slurm-sidecar /slurm-sidecar

USER nonroot:nonroot

ENTRYPOINT ["/slurm-sidecar"]