FROM bitnami/kubectl as kubectl

FROM golang:1.19 as build-stage

WORKDIR /app

COPY .. .

RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -o bin/vk


# Deploy the application binary into a lean image
FROM cgr.dev/chainguard/wolfi-base AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/vk /vk

COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/

USER nonroot:nonroot

ENTRYPOINT ["/vk"]