apiVersion: v1
kind: Pod
metadata:
  name: testvk
  annotations:
    slurm-job.knoc.io/flags: "--job-name=testvkub  -t 2800  --ntasks=8 --nodes=1 --mem-per-cpu=2000"
spec:
  restartPolicy: OnFailure 
  containers:
  - image: /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el8:x86_64
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    command:
      - $HOME/script.sh
    imagePullPolicy: Always
    name: busyecho
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  volumes:
  - name: foo
    configMap:
      name: my-configmap
