apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    slurm-job.knoc.io/flags: "--job-name=testvkub  -t 2800  --ntasks=8 --nodes=1 --mem-per-cpu=2000"
spec:
  restartPolicy: OnFailure 
  containers:
  #- image: /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el8:x86_64
  - image: docker://busybox:latest
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    command:
      - sleep
      - infinity
    imagePullPolicy: Always
    name: busyecho
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
    kubernetes.io/hostname: test-vk
  tolerations:
  - key: virtual-node.interlink/no-schedule
    operator: Exists
  volumes:
  - name: foo
    configMap:
      name: my-configmap
  - name: foo2
    secret:
      secretName: mysecret