apiVersion: v1
kind: Pod
metadata:
  name: interlink-quickstart
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: my-civo-node
  automountServiceAccountToken: false
  containers:
  - args:
    - "\"600\"" 
    command:
    - sleep 
    image: ubuntu 
    imagePullPolicy: Always
    name: my-container
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
  tolerations:
  - key: virtual-node.interlink/no-schedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

